version: "3"
services:
  ledger:
    image: ccarcaci/nodemon:alpine
    command: nodemon --inspect=0.0.0.0 ledger/src/index.js
    volumes: 
      - ../ledger:/ledger
    environment:
      MINING_INTERVAL: 1000
      LOG_LEVEL: debug
    ports:
      - 3000:3000
      - 4443:4443
      - 9229:9229
