version: "3"
services:
  operator:
    image: node:alpine
    command: node --inspect=0.0.0.0 ledger-operator/index.js
    volumes: 
      - ../ledger-operator:/ledger-operator
    environment:
      REF_NODE_URL: http://tracker:3000/track
      LOG_LEVEL: debug
    depends_on:
      - tracker
    ports:
      - 3000
      - 4443
      - 9229
  tracker:
    image: node:alpine
    command: node --inspect=0.0.0.0 tracker/index.js
    volumes:
      - ../tracker:/tracker
    ports:
      - 4242:3000
      - 4243:4443
      - 4229:9229
